### ISSUE TITLE
Outcomes

### ISSUE THREAD

**Issue by mhart** [dshaw/node-error-handling#1]
Were any discussions or outcomes documented anywhere? Would love to see 'em if so!

**Comment by rvagg** [comment]
@mhart some details here: https://nodefirm.hackpad.com/Node-Error-Handling-Summit-uXFi4FUg8Td

I'll try and do a write-up when I can so everyone can be in the loop.

**Comment by mhart** [comment]
Awesome, thanks dude!

**Comment by mhart** [comment]
Closing
